// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuz6lWRufA1TJx3zNe4RAWRuvvBH2Fcg',
    appId: '1:120287924844:web:4cbd095851acf72e61be49',
    messagingSenderId: '120287924844',
    projectId: 'assignment1-375eb',
    authDomain: 'assignment1-375eb.firebaseapp.com',
    storageBucket: 'assignment1-375eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmp4Gb3C3cpbYsFJh70jChcUEvrAmnK5I',
    appId: '1:120287924844:android:8a7d221e8a7beaf661be49',
    messagingSenderId: '120287924844',
    projectId: 'assignment1-375eb',
    storageBucket: 'assignment1-375eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXOCnyD74urOG4o__kGrgzEmYEf4n5Jk',
    appId: '1:120287924844:ios:08c32928480c503261be49',
    messagingSenderId: '120287924844',
    projectId: 'assignment1-375eb',
    storageBucket: 'assignment1-375eb.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXOCnyD74urOG4o__kGrgzEmYEf4n5Jk',
    appId: '1:120287924844:ios:08c32928480c503261be49',
    messagingSenderId: '120287924844',
    projectId: 'assignment1-375eb',
    storageBucket: 'assignment1-375eb.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUuz6lWRufA1TJx3zNe4RAWRuvvBH2Fcg',
    appId: '1:120287924844:web:fdcfd5e7c5f6f6a761be49',
    messagingSenderId: '120287924844',
    projectId: 'assignment1-375eb',
    authDomain: 'assignment1-375eb.firebaseapp.com',
    storageBucket: 'assignment1-375eb.firebasestorage.app',
  );
}
